name: Build and deploy the toolbox image
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 6 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Publish image to DockerHub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: protyro/toolbox-pentest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          buildoptions: "--compress --force-rm"
